from fastapi import APIRouter
from pydantic import BaseModel
from app.services.graphrag_service import GraphRAGService

router = APIRouter(prefix="/api/graphrag", tags=["GraphRAG"])

class GraphRAGQuery(BaseModel):
    question: str

@router.post("/query")
def query_graphrag(payload: GraphRAGQuery):
    # Pass none for graph_service since we are mocking
    service = GraphRAGService(graph_service=None)
    context = service.retrieve_context(payload.question)
    return {
        "question": payload.question,
        "answer": "This is a mocked answer generated by evaluating the retrieved GraphRAG context.",
        "context_used": context
    }
